/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.
const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:6eb78f94-5588-4031-815e-a0c79fb75bb0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_TdK5Bbdsf",
    "aws_user_pools_web_client_id": "u6119067tkli98fmuf7k1o4oo",
    "oauth": {},
    "aws_user_files_s3_bucket": "rckeeluploadvideobuckettest1113114-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};
export default awsmobile;